LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name            | Type               | Params | Mode
---------------------------------------------------------------
0 | embedding       | Sequential         | 17.0 K | train
1 | transformer     | TransformerEncoder | 529 K  | train
2 | regression_head | Sequential         | 8.3 K  | train
---------------------------------------------------------------
555 K     Trainable params
0         Non-trainable params
555 K     Total params
2.221     Total estimated model params size (MB)
59        Modules in train mode
0         Modules in eval mode
Traceback (most recent call last):
  File "/home/oepeng_aims_ac_za/Code/TrackFormer/main.py", line 12, in <module>
    cli_main()
  File "/home/oepeng_aims_ac_za/Code/TrackFormer/main.py", line 8, in cli_main
    cli = LightningCLI()
          ^^^^^^^^^^^^^^
  File "/home/oepeng_aims_ac_za/.local/lib/python3.12/site-packages/lightning/pytorch/cli.py", line 394, in __init__
    self._run_subcommand(self.subcommand)
  File "/home/oepeng_aims_ac_za/.local/lib/python3.12/site-packages/lightning/pytorch/cli.py", line 701, in _run_subcommand
    fn(**fn_kwargs)
  File "/home/oepeng_aims_ac_za/.local/lib/python3.12/site-packages/lightning/pytorch/trainer/trainer.py", line 538, in fit
    call._call_and_handle_interrupt(
  File "/home/oepeng_aims_ac_za/.local/lib/python3.12/site-packages/lightning/pytorch/trainer/call.py", line 47, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oepeng_aims_ac_za/.local/lib/python3.12/site-packages/lightning/pytorch/trainer/trainer.py", line 574, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/oepeng_aims_ac_za/.local/lib/python3.12/site-packages/lightning/pytorch/trainer/trainer.py", line 981, in _run
    results = self._run_stage()
              ^^^^^^^^^^^^^^^^^
  File "/home/oepeng_aims_ac_za/.local/lib/python3.12/site-packages/lightning/pytorch/trainer/trainer.py", line 1025, in _run_stage
    self.fit_loop.run()
  File "/home/oepeng_aims_ac_za/.local/lib/python3.12/site-packages/lightning/pytorch/loops/fit_loop.py", line 197, in run
    self.setup_data()
  File "/home/oepeng_aims_ac_za/.local/lib/python3.12/site-packages/lightning/pytorch/loops/fit_loop.py", line 225, in setup_data
    train_dataloader = _request_dataloader(source)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oepeng_aims_ac_za/.local/lib/python3.12/site-packages/lightning/pytorch/trainer/connectors/data_connector.py", line 325, in _request_dataloader
    return data_source.dataloader()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oepeng_aims_ac_za/.local/lib/python3.12/site-packages/lightning/pytorch/trainer/connectors/data_connector.py", line 289, in dataloader
    return call._call_lightning_module_hook(self.instance.trainer, self.name, pl_module=self.instance)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oepeng_aims_ac_za/.local/lib/python3.12/site-packages/lightning/pytorch/trainer/call.py", line 167, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/oepeng_aims_ac_za/.local/lib/python3.12/site-packages/lightning/pytorch/core/hooks.py", line 482, in train_dataloader
    raise MisconfigurationException("`train_dataloader` must be implemented to be used with the Lightning Trainer")
lightning.fabric.utilities.exceptions.MisconfigurationException: `train_dataloader` must be implemented to be used with the Lightning Trainer
